// Generated by gencpp from file nasa_r2_common_msgs/ForceControlAxis.msg
// DO NOT EDIT!


#ifndef NASA_R2_COMMON_MSGS_MESSAGE_FORCECONTROLAXIS_H
#define NASA_R2_COMMON_MSGS_MESSAGE_FORCECONTROLAXIS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nasa_r2_common_msgs
{
template <class ContainerAllocator>
struct ForceControlAxis_
{
  typedef ForceControlAxis_<ContainerAllocator> Type;

  ForceControlAxis_()
    : axis()
    , magnitude()  {
    }
  ForceControlAxis_(const ContainerAllocator& _alloc)
    : axis(_alloc)
    , magnitude(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _axis_type;
  _axis_type axis;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _magnitude_type;
  _magnitude_type magnitude;


    enum { X = 0u };
     enum { Y = 1u };
     enum { Z = 2u };
     enum { ROLL = 3u };
     enum { PITCH = 4u };
     enum { YAW = 5u };
 

  typedef boost::shared_ptr< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> const> ConstPtr;

}; // struct ForceControlAxis_

typedef ::nasa_r2_common_msgs::ForceControlAxis_<std::allocator<void> > ForceControlAxis;

typedef boost::shared_ptr< ::nasa_r2_common_msgs::ForceControlAxis > ForceControlAxisPtr;
typedef boost::shared_ptr< ::nasa_r2_common_msgs::ForceControlAxis const> ForceControlAxisConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nasa_r2_common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'nasa_r2_common_msgs': ['/home/vincent/Project/r2_sim/src/deprecated_nasa_r2_common/nasa_r2_common_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8efe484fba93bec26ea428bb18a05f9";
  }

  static const char* value(const ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8efe484fba93becULL;
  static const uint64_t static_value2 = 0x26ea428bb18a05f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nasa_r2_common_msgs/ForceControlAxis";
  }

  static const char* value(const ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] axis\n\
float32[] magnitude\n\
\n\
uint8 X       = 0\n\
uint8 Y       = 1\n\
uint8 Z       = 2\n\
uint8 ROLL    = 3\n\
uint8 PITCH   = 4\n\
uint8 YAW     = 5\n\
";
  }

  static const char* value(const ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axis);
      stream.next(m.magnitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForceControlAxis_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nasa_r2_common_msgs::ForceControlAxis_<ContainerAllocator>& v)
  {
    s << indent << "axis[]" << std::endl;
    for (size_t i = 0; i < v.axis.size(); ++i)
    {
      s << indent << "  axis[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.axis[i]);
    }
    s << indent << "magnitude[]" << std::endl;
    for (size_t i = 0; i < v.magnitude.size(); ++i)
    {
      s << indent << "  magnitude[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.magnitude[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NASA_R2_COMMON_MSGS_MESSAGE_FORCECONTROLAXIS_H
