// Generated by gencpp from file nasa_r2_common_msgs/JointTrajectoryReplan.msg
// DO NOT EDIT!


#ifndef NASA_R2_COMMON_MSGS_MESSAGE_JOINTTRAJECTORYREPLAN_H
#define NASA_R2_COMMON_MSGS_MESSAGE_JOINTTRAJECTORYREPLAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nasa_r2_common_msgs/ReplanType.h>
#include <trajectory_msgs/JointTrajectory.h>

namespace nasa_r2_common_msgs
{
template <class ContainerAllocator>
struct JointTrajectoryReplan_
{
  typedef JointTrajectoryReplan_<ContainerAllocator> Type;

  JointTrajectoryReplan_()
    : header()
    , replan()
    , trajectory()  {
    }
  JointTrajectoryReplan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , replan(_alloc)
    , trajectory(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::nasa_r2_common_msgs::ReplanType_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nasa_r2_common_msgs::ReplanType_<ContainerAllocator> >::other >  _replan_type;
  _replan_type replan;

   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _trajectory_type;
  _trajectory_type trajectory;




  typedef boost::shared_ptr< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> const> ConstPtr;

}; // struct JointTrajectoryReplan_

typedef ::nasa_r2_common_msgs::JointTrajectoryReplan_<std::allocator<void> > JointTrajectoryReplan;

typedef boost::shared_ptr< ::nasa_r2_common_msgs::JointTrajectoryReplan > JointTrajectoryReplanPtr;
typedef boost::shared_ptr< ::nasa_r2_common_msgs::JointTrajectoryReplan const> JointTrajectoryReplanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nasa_r2_common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'nasa_r2_common_msgs': ['/home/vincent/Project/r2_sim/src/deprecated_nasa_r2_common/nasa_r2_common_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "282383b42345996d1c9b14b7391111c8";
  }

  static const char* value(const ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x282383b42345996dULL;
  static const uint64_t static_value2 = 0x1c9b14b7391111c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nasa_r2_common_msgs/JointTrajectoryReplan";
  }

  static const char* value(const ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
ReplanType[] replan\n\
trajectory_msgs/JointTrajectory trajectory\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: nasa_r2_common_msgs/ReplanType\n\
uint8 type\n\
\n\
uint8 NONE = 0\n\
uint8 SOFT = 1\n\
uint8 HARD = 2\n\
uint8 STOP = 3\n\
uint8 PAUSE = 4\n\
uint8 CONTINUE = 5\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectory\n\
Header header\n\
string[] joint_names\n\
JointTrajectoryPoint[] points\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectoryPoint\n\
# Each trajectory point specifies either positions[, velocities[, accelerations]]\n\
# or positions[, effort] for the trajectory to be executed.\n\
# All specified values are in the same order as the joint names in JointTrajectory.msg\n\
\n\
float64[] positions\n\
float64[] velocities\n\
float64[] accelerations\n\
float64[] effort\n\
duration time_from_start\n\
";
  }

  static const char* value(const ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.replan);
      stream.next(m.trajectory);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointTrajectoryReplan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nasa_r2_common_msgs::JointTrajectoryReplan_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "replan[]" << std::endl;
    for (size_t i = 0; i < v.replan.size(); ++i)
    {
      s << indent << "  replan[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nasa_r2_common_msgs::ReplanType_<ContainerAllocator> >::stream(s, indent + "    ", v.replan[i]);
    }
    s << indent << "trajectory: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NASA_R2_COMMON_MSGS_MESSAGE_JOINTTRAJECTORYREPLAN_H
