// Generated by gencpp from file nasa_r2_common_msgs/PowerState.msg
// DO NOT EDIT!


#ifndef NASA_R2_COMMON_MSGS_MESSAGE_POWERSTATE_H
#define NASA_R2_COMMON_MSGS_MESSAGE_POWERSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nasa_r2_common_msgs
{
template <class ContainerAllocator>
struct PowerState_
{
  typedef PowerState_<ContainerAllocator> Type;

  PowerState_()
    : data(0)  {
    }
  PowerState_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;


    enum { UNKNOWN = 0u };
     enum { POWER_OFF = 1u };
     enum { LOGIC_POWER = 2u };
     enum { MOTOR_POWER = 3u };
     enum { MOTOR48_POWER = 4u };
     enum { MOTOR96_POWER = 5u };
     enum { FAULTED = 6u };
     enum { TRANSITIONING = 7u };
     enum { IGNORE = 8u };
 

  typedef boost::shared_ptr< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> const> ConstPtr;

}; // struct PowerState_

typedef ::nasa_r2_common_msgs::PowerState_<std::allocator<void> > PowerState;

typedef boost::shared_ptr< ::nasa_r2_common_msgs::PowerState > PowerStatePtr;
typedef boost::shared_ptr< ::nasa_r2_common_msgs::PowerState const> PowerStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nasa_r2_common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'nasa_r2_common_msgs': ['/home/vincent/Project/r2_sim/src/deprecated_nasa_r2_common/nasa_r2_common_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "584ec0c2e2cf9b94d0b9da5027668714";
  }

  static const char* value(const ::nasa_r2_common_msgs::PowerState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x584ec0c2e2cf9b94ULL;
  static const uint64_t static_value2 = 0xd0b9da5027668714ULL;
};

template<class ContainerAllocator>
struct DataType< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nasa_r2_common_msgs/PowerState";
  }

  static const char* value(const ::nasa_r2_common_msgs::PowerState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 data\n\
uint8 UNKNOWN       = 0\n\
uint8 POWER_OFF     = 1\n\
uint8 LOGIC_POWER   = 2\n\
uint8 MOTOR_POWER   = 3\n\
uint8 MOTOR48_POWER = 4\n\
uint8 MOTOR96_POWER = 5\n\
uint8 FAULTED       = 6\n\
uint8 TRANSITIONING = 7\n\
uint8 IGNORE        = 8\n\
";
  }

  static const char* value(const ::nasa_r2_common_msgs::PowerState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PowerState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nasa_r2_common_msgs::PowerState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nasa_r2_common_msgs::PowerState_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NASA_R2_COMMON_MSGS_MESSAGE_POWERSTATE_H
