// Generated by gencpp from file nasa_r2_common_msgs/TakeSnapshot.msg
// DO NOT EDIT!


#ifndef NASA_R2_COMMON_MSGS_MESSAGE_TAKESNAPSHOT_H
#define NASA_R2_COMMON_MSGS_MESSAGE_TAKESNAPSHOT_H

#include <ros/service_traits.h>


#include <nasa_r2_common_msgs/TakeSnapshotRequest.h>
#include <nasa_r2_common_msgs/TakeSnapshotResponse.h>


namespace nasa_r2_common_msgs
{

struct TakeSnapshot
{

typedef TakeSnapshotRequest Request;
typedef TakeSnapshotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakeSnapshot
} // namespace nasa_r2_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nasa_r2_common_msgs::TakeSnapshot > {
  static const char* value()
  {
    return "e8c32298170b230d5efde1ef2dc16bd2";
  }

  static const char* value(const ::nasa_r2_common_msgs::TakeSnapshot&) { return value(); }
};

template<>
struct DataType< ::nasa_r2_common_msgs::TakeSnapshot > {
  static const char* value()
  {
    return "nasa_r2_common_msgs/TakeSnapshot";
  }

  static const char* value(const ::nasa_r2_common_msgs::TakeSnapshot&) { return value(); }
};


// service_traits::MD5Sum< ::nasa_r2_common_msgs::TakeSnapshotRequest> should match 
// service_traits::MD5Sum< ::nasa_r2_common_msgs::TakeSnapshot > 
template<>
struct MD5Sum< ::nasa_r2_common_msgs::TakeSnapshotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nasa_r2_common_msgs::TakeSnapshot >::value();
  }
  static const char* value(const ::nasa_r2_common_msgs::TakeSnapshotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nasa_r2_common_msgs::TakeSnapshotRequest> should match 
// service_traits::DataType< ::nasa_r2_common_msgs::TakeSnapshot > 
template<>
struct DataType< ::nasa_r2_common_msgs::TakeSnapshotRequest>
{
  static const char* value()
  {
    return DataType< ::nasa_r2_common_msgs::TakeSnapshot >::value();
  }
  static const char* value(const ::nasa_r2_common_msgs::TakeSnapshotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nasa_r2_common_msgs::TakeSnapshotResponse> should match 
// service_traits::MD5Sum< ::nasa_r2_common_msgs::TakeSnapshot > 
template<>
struct MD5Sum< ::nasa_r2_common_msgs::TakeSnapshotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nasa_r2_common_msgs::TakeSnapshot >::value();
  }
  static const char* value(const ::nasa_r2_common_msgs::TakeSnapshotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nasa_r2_common_msgs::TakeSnapshotResponse> should match 
// service_traits::DataType< ::nasa_r2_common_msgs::TakeSnapshot > 
template<>
struct DataType< ::nasa_r2_common_msgs::TakeSnapshotResponse>
{
  static const char* value()
  {
    return DataType< ::nasa_r2_common_msgs::TakeSnapshot >::value();
  }
  static const char* value(const ::nasa_r2_common_msgs::TakeSnapshotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NASA_R2_COMMON_MSGS_MESSAGE_TAKESNAPSHOT_H
