// Generated by gencpp from file nasa_r2_common_msgs/TorsoStatus.msg
// DO NOT EDIT!


#ifndef NASA_R2_COMMON_MSGS_MESSAGE_TORSOSTATUS_H
#define NASA_R2_COMMON_MSGS_MESSAGE_TORSOSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nasa_r2_common_msgs
{
template <class ContainerAllocator>
struct TorsoStatus_
{
  typedef TorsoStatus_<ContainerAllocator> Type;

  TorsoStatus_()
    : leftarm()
    , rightarm()
    , neck()
    , lefthand()
    , righthand()
    , waist()  {
    }
  TorsoStatus_(const ContainerAllocator& _alloc)
    : leftarm(_alloc)
    , rightarm(_alloc)
    , neck(_alloc)
    , lefthand(_alloc)
    , righthand(_alloc)
    , waist(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _leftarm_type;
  _leftarm_type leftarm;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _rightarm_type;
  _rightarm_type rightarm;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _neck_type;
  _neck_type neck;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lefthand_type;
  _lefthand_type lefthand;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _righthand_type;
  _righthand_type righthand;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _waist_type;
  _waist_type waist;




  typedef boost::shared_ptr< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TorsoStatus_

typedef ::nasa_r2_common_msgs::TorsoStatus_<std::allocator<void> > TorsoStatus;

typedef boost::shared_ptr< ::nasa_r2_common_msgs::TorsoStatus > TorsoStatusPtr;
typedef boost::shared_ptr< ::nasa_r2_common_msgs::TorsoStatus const> TorsoStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nasa_r2_common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'nasa_r2_common_msgs': ['/home/vincent/Project/r2_sim/src/deprecated_nasa_r2_common/nasa_r2_common_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2334ce336aad886ccb87a294113ed892";
  }

  static const char* value(const ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2334ce336aad886cULL;
  static const uint64_t static_value2 = 0xcb87a294113ed892ULL;
};

template<class ContainerAllocator>
struct DataType< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nasa_r2_common_msgs/TorsoStatus";
  }

  static const char* value(const ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string leftarm\n\
string rightarm\n\
string neck\n\
string lefthand\n\
string righthand\n\
string waist\n\
";
  }

  static const char* value(const ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftarm);
      stream.next(m.rightarm);
      stream.next(m.neck);
      stream.next(m.lefthand);
      stream.next(m.righthand);
      stream.next(m.waist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TorsoStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nasa_r2_common_msgs::TorsoStatus_<ContainerAllocator>& v)
  {
    s << indent << "leftarm: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.leftarm);
    s << indent << "rightarm: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.rightarm);
    s << indent << "neck: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.neck);
    s << indent << "lefthand: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lefthand);
    s << indent << "righthand: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.righthand);
    s << indent << "waist: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.waist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NASA_R2_COMMON_MSGS_MESSAGE_TORSOSTATUS_H
