(cl:in-package gazebo_taskboard-msg)
(cl:export '(PANEL_POWER_COVER-VAL
          PANEL_POWER_COVER
          PANEL_POWER_SWITCH-VAL
          PANEL_POWER_SWITCH
          PANEL_POWER_LED-VAL
          PANEL_POWER_LED
          A01_ROCKER_SWITCH-VAL
          A01_ROCKER_SWITCH
          A01_ROCKER_LED_TOP-VAL
          A01_ROCKER_LED_TOP
          A01_ROCKER_LED_BOTTOM-VAL
          A01_ROCKER_LED_BOTTOM
          A02_LED_NUM_PAD_A1-VAL
          A02_LED_NUM_PAD_A1
          A02_LED_NUM_PAD_A2-VAL
          A02_LED_NUM_PAD_A2
          A02_LED_NUM_PAD_A3-VAL
          A02_LED_NUM_PAD_A3
          A02_LED_NUM_PAD_B1-VAL
          A02_LED_NUM_PAD_B1
          A02_LED_NUM_PAD_B2-VAL
          A02_LED_NUM_PAD_B2
          A02_LED_NUM_PAD_B3-VAL
          A02_LED_NUM_PAD_B3
          A02_LED_NUM_PAD_C1-VAL
          A02_LED_NUM_PAD_C1
          A02_LED_NUM_PAD_C2-VAL
          A02_LED_NUM_PAD_C2
          A02_LED_NUM_PAD_C3-VAL
          A02_LED_NUM_PAD_C3
          A02_NUM_PAD_A1-VAL
          A02_NUM_PAD_A1
          A02_NUM_PAD_A2-VAL
          A02_NUM_PAD_A2
          A02_NUM_PAD_A3-VAL
          A02_NUM_PAD_A3
          A02_NUM_PAD_B1-VAL
          A02_NUM_PAD_B1
          A02_NUM_PAD_B2-VAL
          A02_NUM_PAD_B2
          A02_NUM_PAD_B3-VAL
          A02_NUM_PAD_B3
          A02_NUM_PAD_C1-VAL
          A02_NUM_PAD_C1
          A02_NUM_PAD_C2-VAL
          A02_NUM_PAD_C2
          A02_NUM_PAD_C3-VAL
          A02_NUM_PAD_C3
          A03_TOGGLE-VAL
          A03_TOGGLE
          A03_LED-VAL
          A03_LED
          A04_TOGGLE-VAL
          A04_TOGGLE
          A04_LED_TOP-VAL
          A04_LED_TOP
          A04_LED_BOTTOM-VAL
          A04_LED_BOTTOM
          A05_TOGGLE-VAL
          A05_TOGGLE
          A05_LED-VAL
          A05_LED
))