(cl:in-package nasa_r2_common_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NAME-VAL
          NAME
          DESIREDPOSITION-VAL
          DESIREDPOSITION
          DESIREDPOSITIONVELOCITYLIMIT-VAL
          DESIREDPOSITIONVELOCITYLIMIT
          FEEDFORWARDTORQUE-VAL
          FEEDFORWARDTORQUE
          PROPORTIONALGAIN-VAL
          PROPORTIONALGAIN
          DERIVATIVEGAIN-VAL
          DERIVATIVEGAIN
          INTEGRALGAIN-VAL
          INTEGRALGAIN
          POSITIONLOOPTORQUELIMIT-VAL
          POSITIONLOOPTORQUELIMIT
          POSITIONLOOPWINDUPLIMIT-VAL
          POSITIONLOOPWINDUPLIMIT
          TORQUELOOPVELOCITYLIMIT-VAL
          TORQUELOOPVELOCITYLIMIT
))