(cl:in-package nasa_r2_common_msgs-msg)
(cl:export '(MAXLINEARVELOCITY-VAL
          MAXLINEARVELOCITY
          MAXROTATIONALVELOCITY-VAL
          MAXROTATIONALVELOCITY
          MAXLINEARACCELERATION-VAL
          MAXLINEARACCELERATION
          MAXROTATIONALACCELERATION-VAL
          MAXROTATIONALACCELERATION
))