// Generated by gencpp from file gazebo_taskboard/ManipulateNumPadRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_TASKBOARD_MESSAGE_MANIPULATENUMPADREQUEST_H
#define GAZEBO_TASKBOARD_MESSAGE_MANIPULATENUMPADREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_taskboard
{
template <class ContainerAllocator>
struct ManipulateNumPadRequest_
{
  typedef ManipulateNumPadRequest_<ContainerAllocator> Type;

  ManipulateNumPadRequest_()
    : index(0)
    , force(0.0)
    , duration(0.0)  {
    }
  ManipulateNumPadRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , force(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef double _force_type;
  _force_type force;

   typedef double _duration_type;
  _duration_type duration;




  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ManipulateNumPadRequest_

typedef ::gazebo_taskboard::ManipulateNumPadRequest_<std::allocator<void> > ManipulateNumPadRequest;

typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadRequest > ManipulateNumPadRequestPtr;
typedef boost::shared_ptr< ::gazebo_taskboard::ManipulateNumPadRequest const> ManipulateNumPadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gazebo_taskboard

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'gazebo_taskboard': ['/home/vincent/Project/r2_sim/src/deprecated_nasa_r2_simulator/gazebo_taskboard/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa2174eb90f087e819a238e0495526d8";
  }

  static const char* value(const ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa2174eb90f087e8ULL;
  static const uint64_t static_value2 = 0x19a238e0495526d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_taskboard/ManipulateNumPadRequest";
  }

  static const char* value(const ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 index\n\
float64 force\n\
float64 duration\n\
";
  }

  static const char* value(const ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.force);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManipulateNumPadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_taskboard::ManipulateNumPadRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "force: ";
    Printer<double>::stream(s, indent + "  ", v.force);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_TASKBOARD_MESSAGE_MANIPULATENUMPADREQUEST_H
